let employees = ['John', 'Sarah', 'Eric'];
employees.push('Brad');
console.log(employees);
employees.pop();
console.log(employees);
employees.unshift('Brad');
console.log(employees);
let sarahIndex = employees.indexOf("Sarah");
console.log(sarahIndex);
let salaries = [35000, 45000, 55000, 70000, 90000];
let fin = salaries.filter(salaries => salaries > 50000);
console.log(fin);
let sql = salaries.map(salaries => salaries ** 2);
console.log(sql);
let low = salaries.find(salaries => salaries < 60000);
console.log(low);
let sales = [100, 200, 150, 300, 400];
let sum = sales.reduce((sum, item) => sum + item, 0);
console.log(sum);
let departments = ['HR', 'Finance', 'Engineering', 'Marketing'];
departments.forEach(department => {console.log(department)});